### PR TITLE
Updated with new favicon

### PR DESCRIPTION
**Pull request by Pratik00019**
Hi @bambooch ,

I have updated the favicon as you suggested and changed its name to better align with standard nomenclature. Could you please review it at your earliest convenience?

Thank you!

### CODE REVIEW

**Comment by nine-codes** [comment]
Can you convert the logo to .ico format and basically replace the favicon.ico with the updated and converted one? :D

**Comment by Pratik00019** [comment]
Hello @bambooch , @nine-codes Updated PR as you said.
Can you pls merge?
Thank you

**Comment by bambooch** [comment]
Hey @Pratik00019 I just spinned up your PR but sadly I don't see the icon being updated in the tab. See screenshot below.

image


Does it work for you? Any extra steps you forgot to mention or commit?

**Review by bambooch — CHANGES_REQUESTED** [review]
please see comment above

**Comment by nine-codes** [comment]
Try incognito as it often is a caching issue @bambooch

**Comment by Pratik00019** [comment]
@bambooch @nine-codes I will replace it with favicon.ico , and will also upload screenshot

**Comment by Pratik00019** [comment]
Hey @bambooch Can you pls check now?
This is the screenshot in my localhost :
image

**Comment by bambooch** [comment]
Managed to get it running on my side to @Pratik00019 Thanks for the effort!

**Review by bambooch — APPROVED** [review]

**Comment by nine-codes** [comment]
Do you want to jojn our discord to be involved in more projects @Pratik00019

**Comment by bambooch** [comment]
Here is the link: https://discord.gg/x2enz95pDF

**Comment by Pratik00019** [comment]
@nine-codes @bambooch  Yes sure, I will be happy to join

**Pull request merged**
