### PR TITLE
Convert station selection comboboxes to shadcn/ui

### PR DESCRIPTION
**Pull request by thryngabriel**
resolve #108 Convert station selection comboboxes to shadcn/ui

I chose the "New York" theme over "Default" out of the two configuration options shown in the [shadcn component reference](https://ui.shadcn.com/docs/components/combobox) because I noticed other UI facelift tasks were using "radix-ui" (New York examples) imports over "lucide-react" (from the Default examples).

This component also has a display string for placeholder text if the search has no results/suggestions, where the previous combobox UI widget did not, so I don't know what text to place there. I would suggest a label value either imported into the StationSelect component (ie doesn't necessarily need to be passed down as another prop), or if the "none found in search" label is not considered important then the line (55 in StationSelect.tsx for now) for the CommandEmpty component could just be removed.

### CODE REVIEW

**Comment by bambooch** [comment]
Hi @thryngabriel thanks for taking time to make a PR! Kudos to the clean commit practice and description/suggestions! 🚀 

Strangely enough, there seems to be an identical error on your PR as well as on #108. There is a Jam recording of the issue on that PR as well for you to see precisely. 

I've yet to solve this issue so please take a look.

**Review by bambooch — CHANGES_REQUESTED** [review]
please look at comment above

**Comment by thryngabriel** [comment]
Interesting. I did a fresh clone of my repo to see whether I could find whatever dependency mismatch is causing this, but I'm also seeing this issue (widgets don't work on first load) on the current main branch. So maybe it is not necessarily related to these component updates?

Attached is a diff between what I found to be the generated pnpm-lock after running `pnpm i` on the main branch (without my changes) and the current pnpm-lock.yaml file as it appears in the main branch of the repo. I'm not familiar enough yet with pnpm to know how exactly this gets generated, but it might help find the packages related if it is a dependency issue.

[pnpm-lock-diff.txt](https://github.com/user-attachments/files/17387644/pnpm-lock-diff.txt)

**Comment by bambooch** [comment]
hi @thryngabriel I found what seems to be the issue and explained on #108 will try to merge it to your PR as well

**Comment by thryngabriel** [comment]
Thanks for the update @bambooch, I'm not really sure how the Calendar prop from #108 would affect this branch/PR since that component is unique to that other PR. So I'm still trying to figure it out from this end. Oddly I am having trouble reproducing the error this morning as well, wondering if it might be browser-specific somehow.

Once you get the Calendar issue solved and merged to main, ping me and I can pull those changes back to my fork and then update this PR, hopefully it's all good!

**Comment by bambooch** [comment]
@thryngabriel haha I cannot believe you wrote that just moments after I wrote another update to #108. Moving to your PR now to see if I can reproduce and fix again. Will keep you posted.

**Review by bambooch — APPROVED** [review]

**Comment by bambooch** [comment]
Well as you said, I cannot reproduce it either. Very strange but finally we can resolve this! Thanks for the effort @thryngabriel

**Comment by thryngabriel** [comment]
I was able to reproduce it in Firefox and Edge, but only from the upstream /main branch. Didn't seem to happen from my fork. Weird. Appreciate the merge, and thanks for sharing your project on Hacktoberfest!

**Pull request merged**
