### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Suvrat1629**
#123  Added the recaptcha configurations to the .env

### CODE REVIEW

**Comment by nine-codes** [comment]
Can't the readme be included in the other PR? Why is it separated into a separate PR?

**Comment by Suvrat1629** [comment]
My apologies, I tried including it in the other PR but it still popped up here i did not intend to do it on purpose, I am also new to open source contribution so I am still trying to figure things out

**Comment by nine-codes** [comment]
No worries, you will get there with time, you should join our discord and be involved in more projects and who knows maybe you make an app that turns into a business hehe

**Comment by Suvrat1629** [comment]
Sure, I also need some help. I was trying to use the website to see how it works but i am not able to select the anything in Odaberite Stanicu Polaska or Odaberite Odredišnu Stanicu, why is it happening?

**Comment by nine-codes** [comment]
Can you join the discord cos it is easier to communicate faster/easier: https://discord.com/invite/R2yKBd42

**Comment by bambooch** [comment]
> My apologies, I tried including it in the other PR but it still popped up here i did not intend to do it on purpose, I am also new to open source contribution so I am still trying to figure things out

I'll close this PR then and you can just include your changes to README as part of #123

**Pull request closed without merging**
